#!/usr/bin/env node
/* shared/themes/build-themes.mjs — regenerate themes.css from the per-theme JSON.
   JSON is canonical; themes.css is GENERATED. Never hand-edit themes.css.

   Run: node build-themes.mjs   (from anywhere; paths resolve to this file's dir)

   What it does:
     - reads _index.json, walks every theme in every group
     - for each non-stub theme with a tokens block, emits a [data-theme="slug"] rule
       (bare --token custom properties, matching the global contract)
     - emits a :root spine from the ultimate fallback (fills any missing key at runtime)
     - validates each token set against the canonical 17-key schema and warns on drift
     - stubs are intentionally skipped (they resolve via the fallback trail at runtime)

   themes.css is a convenience for the static-link path (link the sheet, set data-theme).
   The primary path for hosted apps is resolve.js (fetches JSON live). FileMaker renders
   inline resolved tokens at build time and use neither at runtime.
*/
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const DIR = dirname(fileURLToPath(import.meta.url));
const KEYS = ["bg","surface-1","surface-2","surface-3","border","field","text","text-soft","text-faint","accent","accent-2","accent-soft","on-accent","good","warn","bad","info"];

const idx = JSON.parse(readFileSync(join(DIR, '_index.json'), 'utf8'));
const ultimateSlug = idx.ultimateFallback || 'maw-dark-utility';
const themes = idx.groups.flatMap(g => g.themes);

const blocks = [];
const warnings = [];
let ultimateTokens = null;
let stubCount = 0;

for (const t of themes) {
  if (t.status === 'stub' || !t.file) { stubCount++; continue; }
  const path = join(DIR, t.file);
  if (!existsSync(path)) { warnings.push(`missing file: ${t.file}`); continue; }
  const def = JSON.parse(readFileSync(path, 'utf8'));
  if (!def.tokens) { warnings.push(`${t.slug}: no tokens (status ${t.status}) — skipped`); stubCount++; continue; }

  const have = Object.keys(def.tokens);
  const missing = KEYS.filter(k => !have.includes(k));
  const extra = have.filter(k => !KEYS.includes(k));
  if (missing.length) warnings.push(`${t.slug}: MISSING keys — ${missing.join(', ')}`);
  if (extra.length) warnings.push(`${t.slug}: extra keys — ${extra.join(', ')} (bump schemaVersion if intentional)`);

  const sel = `[data-theme="${t.slug}"]`;
  const lines = KEYS.filter(k => def.tokens[k]).map(k => `  --${k}: ${def.tokens[k]};`).join('\n');
  blocks.push(`${sel}{\n${lines}\n}`);
  if (t.slug === ultimateSlug) ultimateTokens = def.tokens;
}

if (!ultimateTokens) throw new Error(`ultimate fallback theme "${ultimateSlug}" not found or has no tokens`);

const root = `:root{\n${KEYS.map(k => `  --${k}: ${ultimateTokens[k]};`).join('\n')}\n}`;
const stamp = new Date().toISOString().slice(0, 10);

const css = `/* shared/themes/themes.css — GENERATED by build-themes.mjs. DO NOT HAND-EDIT.
   One [data-theme="slug"] block per resolved theme. Stubs are omitted
   (they resolve via the _base fallback spine at runtime).
   Regenerate with: node build-themes.mjs
   Generated: ${stamp} */

/* ultimate fallback spine (${ultimateSlug}); also fills any missing key */
${root}

${blocks.join('\n\n')}\n`;

writeFileSync(join(DIR, 'themes.css'), css);
console.log(`themes.css written — ${blocks.length} theme block(s), ${stubCount} stub(s) skipped.`);
if (warnings.length) { console.log('\nwarnings:'); warnings.forEach(w => console.log('  - ' + w)); }
else { console.log('schema: all resolved themes match the canonical 17-key contract.'); }
