/* shared/themes/preview.data.js — Theme Studio embedded snapshot (SELF-CONTAINED FIRST-PAINT FALLBACK).
   Seeds a safe first paint before preview.core.js's liveOverride() re-fetches the canonical TSV grids +
   _objects.json and overwrites them. Loaded BEFORE preview.core.js.
   Kept in lockstep with the TSVs + _objects.json. T2/T3 (2026-07-18): viewer + input + feedback object
   groups mirrored; their styles live in preview.objects.css. T4 (2026-07-19): retrocast objects
   (card_ribbon, stat_hero_departure, viz_range_band) mirrored. */

/* SELF-CONTAINED EMBED FOR SAFE FIRST PAINT */
var COLORS={
"default-theme":{name:"Default",group:"Utility",mode:"mid",bg:"#8f8f8f","surface-1":"#a0a0a0","surface-2":"#b0b0b0","surface-3":"#bfbfbf",border:"#565656",field:"#ababab",text:"#1c1c1c","text-soft":"#3f3f3f","text-faint":"#5b5b5b",accent:"#353535","accent-deep":"#222222","accent-2":"#515151","accent-soft":"#cccccc","on-accent":"#f6f6f6",good:"#757575",warn:"#656565",bad:"#3f3f3f",info:"#5b5b5b","data-1":"#4f9fe0","data-2":"#e07bad","data-3":"#46c48a","data-4":"#e0a84f"},
"maw-dark-utility":{name:"MAW Dark Utility",group:"Utility",mode:"dark",bg:"#2a2d33","surface-1":"#333740","surface-2":"#3c414b","surface-3":"#434955",border:"#656d7c",field:"#3c414b",text:"#eef0f3","text-soft":"#a7adb8","text-faint":"#7b818d",accent:"#46b8cf","accent-deep":"#2e8ba0","accent-2":"#6fccd6","accent-soft":"#26414a","on-accent":"#10262c",good:"#35c48a",warn:"#d8ab4f",bad:"#d64f3f",info:"#56a8dd","data-1":"#4f9fe0","data-2":"#e07bad","data-3":"#46c48a","data-4":"#e0a84f"},
"carbon":{name:"Carbon",group:"Utility",mode:"dark",bg:"#17181d","surface-1":"#1c1e24","surface-2":"#24272f","surface-3":"#2c3039",border:"#3a3f4b",field:"#24272f",text:"#e8eaef","text-soft":"#a2a8b5","text-faint":"#71778a",accent:"#5b8def","accent-deep":"#3a6bd0","accent-2":"#e07bad","accent-soft":"#23304a","on-accent":"#0f1626",good:"#35c48a",warn:"#d8ab4f",bad:"#d64f3f",info:"#56a0dd","data-1":"#4f9fe0","data-2":"#e07bad","data-3":"#46c48a","data-4":"#e0a84f"},
"mclaren":{name:"McLaren",group:"F1 Dark",mode:"dark",bg:"#292420","surface-1":"#231f1b","surface-2":"#2f2a25","surface-3":"#35302a",border:"#5f5850",field:"#3a342e",text:"#f2f1ec","text-soft":"#5fc9d8","text-faint":"#4c8b98",accent:"#f5842f","accent-deep":"#c05e18","accent-2":"#5fc9d8","accent-soft":"#432f20","on-accent":"#2a1d10",good:"#35c48a",warn:"#d8ab4f",bad:"#d64f3f",info:"#63bce0","data-1":"#4f9fe0","data-2":"#e07bad","data-3":"#46c48a","data-4":"#e0a84f"}
};
var TYPES={
"sharp-racing":{"font-display":"'Chakra Petch', system-ui, sans-serif","font-body":"'Inter', system-ui, sans-serif","font-mono":"'JetBrains Mono', ui-monospace, 'SF Mono', Menlo, monospace","fs-lead":"1rem","fs-body":"0.875rem","fs-sm":"0.8rem","fs-xs":"0.7rem","track-tight":"-0.01em","track-btn":"0.02em"},
"mobile-legible":{"font-display":"'Manrope', system-ui, sans-serif","font-body":"'Manrope', system-ui, sans-serif","font-mono":"'JetBrains Mono', ui-monospace, 'SF Mono', Menlo, monospace","fs-lead":"1.15rem","fs-body":"1.02rem","fs-sm":"0.92rem","fs-xs":"0.8rem","track-tight":"-0.015em","track-btn":"0"},
"grounded":{"font-display":"'Inter', system-ui, sans-serif","font-body":"'Inter', system-ui, sans-serif","font-mono":"'JetBrains Mono', ui-monospace, 'SF Mono', Menlo, monospace","fs-lead":"1.05rem","fs-body":"0.94rem","fs-sm":"0.85rem","fs-xs":"0.75rem","track-tight":"-0.02em","track-btn":"0"}
};
var FORMS={
"sharp":{"radius":"4px","radius-lg":"6px","radius-pill":"6px","border-w":"1.5px","grad-angle":"120deg","shadow-out":"0 1px 2px rgba(0,0,0,0.55), 0 2px 6px rgba(0,0,0,0.35)","shadow-in":"inset 0 2px 4px rgba(0,0,0,0.5)","elev-1":"0 1px 3px rgba(0,0,0,0.42)","elev-2":"0 5px 14px rgba(0,0,0,0.46)","elev-3":"0 14px 32px rgba(0,0,0,0.52)","motion-fast":"120ms","motion-med":"200ms","ease":"cubic-bezier(.2,.7,.2,1)","lift":"-2px"},
"soft":{"radius":"8px","radius-lg":"12px","radius-pill":"8px","border-w":"1px","grad-angle":"135deg","shadow-out":"0 2px 8px rgba(0,0,0,0.22), 0 8px 20px rgba(0,0,0,0.14)","shadow-in":"inset 0 1px 4px rgba(0,0,0,0.24)","elev-1":"0 2px 8px rgba(0,0,0,0.26)","elev-2":"0 9px 24px rgba(0,0,0,0.30)","elev-3":"0 22px 50px rgba(0,0,0,0.38)","motion-fast":"150ms","motion-med":"260ms","ease":"cubic-bezier(.16,1,.3,1)","lift":"-3px"},
"grounded":{"radius":"12px","radius-lg":"18px","radius-pill":"10px","border-w":"1px","grad-angle":"150deg","shadow-out":"0 1px 3px rgba(0,0,0,0.3), 0 4px 12px rgba(0,0,0,0.18)","shadow-in":"inset 0 1px 3px rgba(0,0,0,0.28)","elev-1":"0 3px 12px rgba(0,0,0,0.30)","elev-2":"0 11px 28px rgba(0,0,0,0.34)","elev-3":"0 26px 58px rgba(0,0,0,0.42)","motion-fast":"130ms","motion-med":"240ms","ease":"cubic-bezier(.2,.8,.2,1)","lift":"-3px"}
};
var SPACES={
"tight":{"touch":"42px","pad-cell":"8px","pad-card":"16px","gap-xs":"4px","gap-md":"12px","gap-lg":"24px"},
"loose":{"touch":"52px","pad-cell":"12px","pad-card":"24px","gap-xs":"8px","gap-md":"16px","gap-lg":"32px"},
"standard":{"touch":"44px","pad-cell":"10px","pad-card":"20px","gap-xs":"6px","gap-md":"14px","gap-lg":"28px"}
};

// EMBEDDED OBJECT REGISTRY FALLBACK — mirrors _objects.json. Live fetch overrides. Kept in lockstep.
var REGISTRY={
  "groups": {
    "shells": { "name": "Shells & containers", "desc": "Structural surfaces. Depth from surface fill + border + a tiered elevation shadow.", "objects": [
      { "id":"cnt_page_shell", "name":"Page shell", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"tshell\">Page canvas · app body surface</div>", "props":{ "Fill":"bg", "Line":"border", "Corner":"radius-lg" } } } },
      { "id":"cnt_section_card", "name":"Section card", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"tcard\"><h3>Section card</h3><p>A grouping card holds a related set of fields or content.</p></div>", "props":{ "Fill":"surface-2", "Top rail":"accent-2", "Elevation":"elev-1", "Corner":"radius-lg" } } } },
      { "id":"cnt_toolbar", "name":"Toolbar", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"ttoolbar\"><span class=\"tt\">On Track</span><span class=\"sp\"></span><span class=\"tnav on\">Live</span><span class=\"tnav off\">History</span></div>", "props":{ "Fill":"surface-1", "Title":"text", "Nav on":"accent", "Nav off":"text-faint" } } } },
      { "id":"cnt_filter_bar", "name":"Filter bar", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"ttoolbar\"><span class=\"tnav on\">All</span> <span class=\"tnav off\">Open</span> <span class=\"tnav off\">Closed</span></div>", "props":{ "Fill":"surface-1", "Active chip":"accent", "Idle chip":"text-faint" } } } },
      { "id":"card_modal_standard", "name":"Modal", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"tmodal\"><h3>Confirm action</h3><p>Highest elevation surface.</p><button class=\"tb primary\">Confirm</button></div>", "props":{ "Fill":"surface-3", "Top rail":"accent-2", "Elevation":"elev-3", "Corner":"radius-lg" } } } }
    ] },
    "nav": { "name": "Navigation", "desc": "Active vs inactive must read at a glance.", "objects": [
      { "id":"nav_tab", "name":"Tabs", "rowLayout":true, "states":{ "active":{ "html":"<span class=\"tnav on\">Loans</span> <span class=\"tnav off\">Parties</span> <span class=\"tnav off\">Docs</span>", "props":{ "Active":"accent", "On text":"on-accent", "Inactive":"text-faint" } }, "inactive":{ "html":"<span class=\"tnav off\">Loans</span> <span class=\"tnav off\">Parties</span> <span class=\"tnav off\">Docs</span>", "props":{ "Idle":"text-faint", "Line":"border" } } } },
      { "id":"nav_mode", "name":"Mode toggle", "rowLayout":true, "states":{ "active":{ "html":"<span class=\"tnav on\">List</span> <span class=\"tnav off\">Grid</span>", "props":{ "Selected":"accent", "On text":"on-accent", "Unselected":"text-soft" } } } },
      { "id":"nav_back", "name":"Back affordance", "rowLayout":true, "states":{ "base":{ "html":"<button class=\"tb ghost\">‹ Back to hub</button>", "props":{ "Text":"accent", "Fill":"transparent" } } } }
    ] },
    "type": { "name": "Typography", "desc": "Display + body + mono faces from Typography; ink from Color.", "objects": [
      { "id":"tx_page_title", "name":"Page title", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"ttype\"><div class=\"t1\">Loan application #4021</div></div>", "props":{ "Face":"font-display", "Ink":"text", "Tick":"accent-grad", "Size":"fs-lead" } } } },
      { "id":"tx_section_header", "name":"Section + subsection header", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"ttype\"><div class=\"t2\">Section header</div><div class=\"t2\" style=\"opacity:.7;font-size:0.82rem\">Subsection header</div></div>", "props":{ "Face":"font-display", "Ink":"text" } } } },
      { "id":"tx_field_label", "name":"Field label", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"tfield\"><label>Field label</label></div>", "props":{ "Ink":"text-soft", "Size":"fs-xs" } } } },
      { "id":"tx_body", "name":"Body copy", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"ttype\"><div class=\"t3\">Body copy is the standard reading size for record content and prose in the layout.</div></div>", "props":{ "Ink":"text", "Size":"fs-body" } } } },
      { "id":"tx_mono_data", "name":"Mono data / code", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"ttype\"><div class=\"t3\" style=\"font-family:var(--font-mono);font-variant-numeric:tabular-nums\">1:29.148 &nbsp; +0.204 &nbsp; LAP 47/58</div></div>", "props":{ "Face":"font-mono", "Ink":"text", "Size":"fs-sm" } } } },
      { "id":"tx_helper_muted", "name":"Helper + muted", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"ttype\"><div class=\"t4\">Helper text under a field.</div><div class=\"t5\">Muted metadata · timestamps</div></div>", "props":{ "Helper":"text-soft", "Muted":"text-faint" } } } },
      { "id":"tx_badge", "name":"Text badge", "rowLayout":true, "states":{ "base":{ "html":"<span class=\"tpill accent\">Featured</span>", "props":{ "Fill":"accent-grad", "Text":"on-accent", "Corner":"radius-pill" } } } }
    ] },
    "buttons": { "name": "Buttons — full family", "desc": "Primary is a SOLID accent fill; secondary is a highlight-pink (accent-2) outline. Both lift on hover.", "objects": [
      { "id":"btn_family", "name":"Primary / secondary / quiet / destructive / icon", "rowLayout":true, "states":{ "normal":{ "html":"<button class=\"tb primary\">Primary</button> <button class=\"tb secondary\">Secondary</button> <button class=\"tb ghost\">Quiet</button> <button class=\"tb destructive\">Delete</button> <button class=\"tb icon\">⚙</button>", "props":{ "Primary":"accent", "On text":"on-accent", "Secondary":"accent-2", "Destructive":"bad", "Hover":"elev-2 + lift", "Corner":"radius" } }, "pressed":{ "html":"<button class=\"tb pressed\">Primary</button> <button class=\"tb secondary\" style=\"background:var(--surface-3);box-shadow:var(--shadow-in)\">Secondary</button> <button class=\"tb ghost\">Quiet</button>", "props":{ "Fill":"accent", "Shadow":"shadow-in", "Transform":"translateY(1px)" } } } }
    ] },
    "fields": { "name": "Fields", "desc": "Focus = inner shadow + accent border. Readonly drops to a muted surface.", "objects": [
      { "id":"fd_text_standard", "name":"Text field", "rowLayout":false, "states":{ "editable":{ "html":"<div class=\"tfield\"><label>Driver name</label><input placeholder=\"Type a name...\"></div>", "props":{ "Fill":"field", "Line":"border", "Corner":"radius" } }, "focus":{ "html":"<div class=\"tfield\"><label>Driver name</label><input class=\"focus\" value=\"Lando Norris\"></div>", "props":{ "Line":"accent", "Shadow":"shadow-in" } }, "readonly":{ "html":"<div class=\"tfield\"><label>Team</label><input value=\"McLaren\" readonly style=\"background:var(--surface-2);color:var(--text-soft);pointer-events:none\"></div>", "props":{ "Fill":"surface-2", "Text":"text-soft" } } } },
      { "id":"fd_dropdown_standard", "name":"Dropdown", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"tfield\"><label>Team</label><div class=\"tselect\">McLaren <span>▾</span></div></div>", "props":{ "Fill":"field", "Line":"border", "Chevron":"text-faint" } } } },
      { "id":"fd_readonly_display", "name":"Readonly / calc display", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"tfield\"><label>Computed total</label><div class=\"tro\">$48,210.00</div></div>", "props":{ "Fill":"surface-2", "Text":"text-soft" } } } },
      { "id":"fd_search_filter", "name":"Search field", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"tfield\"><label>Search</label><div class=\"tsearch\"><span>🔍</span><input placeholder=\"Search records...\"></div></div>", "props":{ "Fill":"field", "Icon":"text-faint", "Line":"border" } } } }
    ] },
    "data": { "name": "Rows, tiles & badges", "desc": "Portal rows (hover highlight + selected accent-2 rail), metric tiles (accent-2 top rail), status badges, and a horizontal card ribbon.", "objects": [
      { "id":"row_tile_badge", "name":"Portal rows / metric tiles / status badges", "rowLayout":false, "states":{ "rows":{ "html":"<table class=\"ttable\"><thead><tr><th>Pos</th><th>Driver</th><th class=\"n\">Pts</th></tr></thead><tbody><tr><td>1</td><td>Norris</td><td class=\"n\">287</td></tr><tr class=\"alt\"><td>2</td><td>Piastri</td><td class=\"n\">265</td></tr><tr class=\"sel\"><td>3</td><td>Verstappen</td><td class=\"n\">241</td></tr></tbody></table>", "props":{ "Header":"text-soft", "Alternate":"surface-2", "Selected":"accent-soft", "Selected rail":"accent-2" } }, "tiles":{ "html":"<div style=\"display:flex;gap:12px;flex-wrap:wrap;width:100%\"><div class=\"ttile\"><div class=\"big\">8,412</div><div class=\"lab\">Active this week</div></div><div class=\"ttile\"><div class=\"big\" style=\"color:var(--bad)\">3 overdue</div><div class=\"lab\">Needs attention</div></div></div>", "props":{ "Fill":"surface-2", "Top rail":"accent-2", "Elevation":"elev-1", "Alert":"bad" } }, "badges":{ "html":"<div><span class=\"tpill neutral\">Draft</span> <span class=\"tpill good\">Active</span> <span class=\"tpill warn\">Pending</span> <span class=\"tpill bad\">Overdue</span></div>", "props":{ "Neutral":"surface-3", "Good":"good", "Warn":"warn", "Alert":"bad" } } } },
      { "id":"card_ribbon", "name":"Horizontal card ribbon", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"orib\"><article class=\"orib-card\"><p class=\"orib-y\">1969</p><p class=\"orib-b\">Apollo 11 lands on the Moon.</p></article><article class=\"orib-card\"><p class=\"orib-y\">1976</p><p class=\"orib-b\">Viking 1 touches down on Mars.</p></article><article class=\"orib-card\"><p class=\"orib-y\">2012</p><p class=\"orib-b\">Record heat logged for this calendar day.</p></article></div>", "props":{ "Card fill":"surface-2", "Top rail":"accent-2", "Year":"accent", "Body":"text" } } } }
    ] },
    "viewer": { "name": "Viewer & data-viz", "desc": "Display-side objects for dashboards + record viewers: score meter, prev/next pager, breadcrumb, data-viz legend, departure hero, range-band strip. From f1-racetracks + retrocast.", "objects": [
      { "id":"viz_meter", "name":"Meter / progress bar", "rowLayout":false, "states":{ "inline":{ "html":"<div class=\"ometer\"><span class=\"om-score\">7.4<small>/10</small></span><span class=\"om-track\"><i class=\"om-fill\" style=\"width:74%\"></i></span><span class=\"om-word\">Strong</span></div>", "props":{ "Fill":"accent-grad", "Track":"surface-3", "Score":"font-mono", "Word":"accent" } }, "stacked":{ "html":"<div class=\"ometer stack\"><div class=\"om-top\"><span>Import progress</span><b>68%</b></div><span class=\"om-track\"><i class=\"om-fill\" style=\"width:68%\"></i></span></div>", "props":{ "Fill":"accent-grad", "Track":"surface-3", "Value":"font-mono" } } } },
      { "id":"viz_pager", "name":"Prev / next pager", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"opager\"><button class=\"opn\"><div class=\"opn-l\">Prev</div><div class=\"opn-n\">Silverstone</div></button><button class=\"opn next\"><div class=\"opn-l\">Next</div><div class=\"opn-n\">Hungaroring</div></button></div>", "props":{ "Fill":"surface-2", "Line":"border", "Hover line":"accent", "Label":"font-mono" } } } },
      { "id":"viz_breadcrumb", "name":"Breadcrumb", "rowLayout":true, "states":{ "base":{ "html":"<nav class=\"ocrumb\"><a>Home</a><span class=\"ocb-sep\">/</span><a>Circuits</a><span class=\"ocb-sep\">/</span><span class=\"ocb-cur\">Hungaroring</span></nav>", "props":{ "Face":"font-mono", "Link":"text-soft", "Hover":"accent", "Current":"text" } } } },
      { "id":"viz_legend", "name":"Data-viz legend", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"olegend\"><span class=\"oleg\"><span class=\"osw s1\"></span>Sector 1</span><span class=\"oleg\"><span class=\"osw s2\"></span>Sector 2</span><span class=\"oleg\"><span class=\"osw s3\"></span>Sector 3</span><span class=\"oleg\"><span class=\"oln\"></span>Ideal lap</span></div>", "props":{ "Series 1":"data-1", "Series 2":"data-2", "Series 3":"data-3", "Line":"accent" } } } },
      { "id":"stat_hero_departure", "name":"Departure hero", "rowLayout":false, "states":{ "up":{ "html":"<div class=\"ohero\" data-dir=\"up\"><div class=\"oh-metric\"><span class=\"oh-num\">+6</span><span class=\"oh-unit\">°F</span></div><div class=\"oh-word\">warmer than normal</div><div class=\"oh-sub\">Today 88°F vs. 82°F normal · high temp</div></div>", "props":{ "Number":"text", "Word up":"warn", "Rail up":"warn", "Sub":"text-faint" } }, "down":{ "html":"<div class=\"ohero\" data-dir=\"down\"><div class=\"oh-metric\"><span class=\"oh-num\">-4</span><span class=\"oh-unit\">°F</span></div><div class=\"oh-word\">cooler than normal</div><div class=\"oh-sub\">Today 60°F vs. 64°F normal · high temp</div></div>", "props":{ "Word down":"info", "Rail down":"info" } } } },
      { "id":"viz_range_band", "name":"Range band strip", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"oband\"><span class=\"oband-track\"></span><span class=\"oband-normal\" style=\"left:50%\"></span><span class=\"oband-today\" style=\"left:78%\"></span></div><div class=\"oband-scale\"><span>58°F</span><span>96°F</span></div>", "props":{ "Track":"surface-3", "Normal tick":"text-faint", "Today marker":"accent" } } } }
    ] },
    "input": { "name": "Input & workflow", "desc": "The tool vocabulary: getting data IN + moving through a build. From report-normalizer / budget-code-mapper / prism.", "objects": [
      { "id":"fd_dropzone", "name":"Dropzone", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"odrop\"><div class=\"oico\">⤓</div><h4>Drop a file to begin</h4><p>or click to browse. CSV, JSON, and Markdown supported.</p><div class=\"oexts\"><span class=\"oext\">.csv</span><span class=\"oext\">.json</span><span class=\"oext\">.md</span></div></div>", "props":{ "Fill":"surface-1", "Dashed line":"border", "Hover line":"accent", "Ext tag":"font-mono" } } } },
      { "id":"wf_stepper", "name":"Stepper / progress rail", "rowLayout":true, "states":{ "base":{ "html":"<div class=\"ostep-rail\"><span class=\"ostep done\"><span class=\"on\">✓</span>Upload</span><span class=\"ostep active\"><span class=\"on\">2</span>Map</span><span class=\"ostep\"><span class=\"on\">3</span>Preview</span><span class=\"ostep\"><span class=\"on\">4</span>Export</span></div>", "props":{ "Done":"good", "Active":"accent", "Active fill":"accent-soft", "Idle":"text-faint" } } } },
      { "id":"map_row", "name":"Mapping row", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"omap\"><span class=\"osrc\">source_column_a</span><span class=\"oarrow\">→</span><span class=\"oops\"><span class=\"ochip on\">trim</span><span class=\"ochip\">upper</span><span class=\"ochip\">date</span></span><span class=\"otgt\">Target field <span>▾</span></span></div>", "props":{ "Source":"font-mono", "Op on":"accent", "Target fill":"field", "Line":"border" } } } },
      { "id":"ctl_toggle", "name":"Toggle switch", "rowLayout":true, "states":{ "off":{ "html":"<span class=\"oswitch-row\"><span class=\"oswitch\"></span> Skip empty rows</span>", "props":{ "Track":"surface-3", "Knob":"text-faint" } }, "on":{ "html":"<span class=\"oswitch-row\"><span class=\"oswitch on\"></span> Skip empty rows</span>", "props":{ "Track on":"accent-soft", "Knob on":"accent" } } } },
      { "id":"ctl_chip", "name":"Chip toggle", "rowLayout":true, "states":{ "base":{ "html":"<span class=\"ochip on\">Podiums</span> <span class=\"ochip\">Points</span> <span class=\"ochip\">DNF</span>", "props":{ "On text":"text", "On line":"accent", "On fill":"accent-soft", "Idle":"text-faint" } } } },
      { "id":"ctl_segmented", "name":"Segmented control", "rowLayout":true, "states":{ "base":{ "html":"<div class=\"oseg\"><button class=\"on\">Table</button><button>Tree</button><button>Raw</button></div>", "props":{ "Selected":"accent", "On text":"on-accent", "Idle":"text-soft", "Line":"border" } } } },
      { "id":"btn_icon", "name":"Icon button", "rowLayout":true, "states":{ "base":{ "html":"<button class=\"oiconbtn\">⚙</button> <button class=\"oiconbtn\">↻</button> <button class=\"oiconbtn\">↗</button>", "props":{ "Fill":"surface-2", "Icon":"text-soft", "Hover line":"accent" } } } },
      { "id":"panel_drawer", "name":"Side drawer", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"odrawer\"><div class=\"od-h\"><h4>Settings</h4><button class=\"oiconbtn\">✕</button></div><div class=\"od-b\"><div class=\"od-row\"><span>Theme</span><span class=\"oswitch on\"></span></div><div class=\"od-row\"><span>Auto-refresh</span><span class=\"oswitch\"></span></div><div class=\"od-row\"><span>Compact rows</span><span class=\"oswitch on\"></span></div></div></div>", "props":{ "Fill":"surface-1", "Line":"border", "Elevation":"elev-3", "Corner":"radius-lg" } } } }
    ] },
    "feedback": { "name": "Feedback & data readout", "desc": "How a tool talks back: validation, status, typed data, record-detail readout. From prism / report-normalizer.", "objects": [
      { "id":"fb_banner", "name":"Inline banner / alert", "rowLayout":false, "states":{ "match":{ "html":"<div class=\"obanner match\"><span class=\"ob-ic\">✓</span> All 12 columns matched a target field.</div>", "props":{ "Line":"good", "Tint":"good" } }, "warn":{ "html":"<div class=\"obanner warn\"><span class=\"ob-ic\">⚠</span> 2 columns are unmapped and will be dropped.</div>", "props":{ "Line":"warn", "Tint":"warn" } }, "bad":{ "html":"<div class=\"obanner bad\"><span class=\"ob-ic\">✕</span> Parse failed on row 47: unexpected token.</div>", "props":{ "Line":"bad", "Tint":"bad" } } } },
      { "id":"fb_flag", "name":"Flag / callout item", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"oflag warn\"><span class=\"of-ic\">⚠</span><span><b>Mixed types</b> <span class=\"of-x\">column price has 4 strings among 200 numbers.</span></span></div><div class=\"oflag ok\"><span class=\"of-ic\">✓</span><span><b>Clean key</b> <span class=\"of-x\">id is unique across all rows.</span></span></div>", "props":{ "Warn":"warn", "OK":"good", "Title":"text", "Body":"text-soft" } } } },
      { "id":"data_kv_panel", "name":"KV stat panel", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"okv\"><div class=\"okv-h\">File stats</div><div class=\"okv-row\"><span class=\"okv-k\">Rows</span><span class=\"okv-v\">8,412</span></div><div class=\"okv-row\"><span class=\"okv-k\">Columns</span><span class=\"okv-v\">12</span></div><div class=\"okv-row\"><span class=\"okv-k\">Size</span><span class=\"okv-v\">1.9 MB</span></div></div>", "props":{ "Fill":"surface-1", "Key":"text-soft", "Value":"font-mono", "Elevation":"elev-1" } } } },
      { "id":"data_typed_table", "name":"Typed data table", "rowLayout":false, "states":{ "base":{ "html":"<div class=\"otblwrap\"><table class=\"otbl\"><thead><tr><th class=\"orownum\">#</th><th>id<span class=\"oty\">int</span></th><th>name<span class=\"oty\">string</span></th><th>active<span class=\"oty\">bool</span></th></tr></thead><tbody><tr><td class=\"orownum\">1</td><td><span class=\"onum\">1001</span></td><td>Norris</td><td><span class=\"obool\">true</span></td></tr><tr><td class=\"orownum\">2</td><td><span class=\"onum\">1002</span></td><td>Piastri</td><td><span class=\"obool\">true</span></td></tr><tr><td class=\"orownum\">3</td><td><span class=\"onum\">1003</span></td><td><span class=\"onull\">null</span></td><td><span class=\"obool\">false</span></td></tr></tbody></table></div>", "props":{ "Header":"surface-2", "Type label":"font-mono", "Number":"data-1", "Bool":"data-2", "Null":"text-faint" } } } },
      { "id":"fb_toast", "name":"Toast", "rowLayout":true, "states":{ "base":{ "html":"<span class=\"otoast\"><span class=\"ot-ic\">✓</span> Copied to clipboard</span>", "props":{ "Fill":"surface-3", "Icon":"good", "Elevation":"elev-2" } } } },
      { "id":"fb_empty", "name":"Empty / error state", "rowLayout":false, "states":{ "empty":{ "html":"<div class=\"oempty\"><div class=\"oe-ic\">□</div><h4>No records yet</h4><p>Import a file or add a row to get started.</p></div>", "props":{ "Icon fill":"surface-2", "Title":"text", "Body":"text-soft" } }, "error":{ "html":"<div class=\"oempty err\"><div class=\"oe-ic\">✕</div><h4>Couldn't load data</h4><p>The source returned a 404. Check the path and retry.</p></div>", "props":{ "Icon":"bad", "Title":"text", "Body":"text-soft" } } } }
    ] }
  }
};

var GROUPS={"default-theme":"Utility","maw-dark-utility":"Utility","carbon":"Utility","mclaren":"F1 Dark"};
var ROLES={bg:"page canvas","surface-1":"toolbar/header","surface-2":"card / row alt","surface-3":"modal / raised",border:"lines & edges",field:"input fill",text:"primary text","text-soft":"secondary text","text-faint":"muted/helper",accent:"actionable · grad start","accent-deep":"deep shade (spare)","accent-2":"gradient 2nd stop · pop","accent-soft":"tint / selected","on-accent":"text on accent",good:"success",warn:"warning",bad:"error/destructive",info:"informational","data-1":"chart series 1","data-2":"chart series 2","data-3":"chart series 3","data-4":"chart series 4"};
var SW_ORDER=["bg","surface-1","surface-2","surface-3","border","field","text","text-soft","text-faint","accent","accent-deep","accent-2","accent-soft","on-accent","good","warn","bad","info","data-1","data-2","data-3","data-4"];

var CHROME={
  light:{"--ch-bg":"oklch(0.93 0.005 265)","--ch-panel":"oklch(0.98 0.003 265)","--ch-sunk":"oklch(0.905 0.006 265)","--ch-line":"oklch(0.85 0.012 265)","--ch-ink":"oklch(0.24 0.02 275)","--ch-soft":"oklch(0.46 0.02 275)","--ch-faint":"oklch(0.60 0.02 275)","--ch-accent":"oklch(0.54 0.16 275)","--ch-accent-soft":"oklch(0.90 0.04 275)"},
  mid:{"--ch-bg":"oklch(0.86 0.004 265)","--ch-panel":"oklch(0.92 0.003 265)","--ch-sunk":"oklch(0.83 0.005 265)","--ch-line":"oklch(0.74 0.010 265)","--ch-ink":"oklch(0.20 0.02 275)","--ch-soft":"oklch(0.38 0.02 275)","--ch-faint":"oklch(0.50 0.02 275)","--ch-accent":"oklch(0.42 0.16 275)","--ch-accent-soft":"oklch(0.80 0.05 275)"},
  dark:{"--ch-bg":"oklch(0.24 0.008 265)","--ch-panel":"oklch(0.29 0.010 265)","--ch-sunk":"oklch(0.21 0.008 265)","--ch-line":"oklch(0.40 0.014 265)","--ch-ink":"oklch(0.95 0.006 265)","--ch-soft":"oklch(0.74 0.010 265)","--ch-faint":"oklch(0.58 0.010 265)","--ch-accent":"oklch(0.72 0.13 265)","--ch-accent-soft":"oklch(0.34 0.05 265)"}
};
